version: "3.7"

services:
  mongo:        
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27019:27017"
    networks:
      - tesina-network
  transporteapimono:
    container_name: transporteapimono
    build:
      context: ./mono/TransporteApiMono
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - mongo
    networks:
      - tesina-network

networks:
  tesina-network:
    driver: bridge